services:
  - type: web
    name: mini-social
    env: node
    plan: free
    rootDir: backend

    buildCommand: npm ci && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start

    envVars:
      - key: DATABASE_URL
        value: file:./prisma/dev.db

      - key: JWT_SECRET
        generateValue: true

      - key: JWT_EXPIRES_IN
        value: 7d

      - key: CORS_ORIGIN
        value: "*"
